### ISSUE TITLE
Set PKGBUILD architecture to any

### ISSUE THREAD

**Issue by pintergreg** [sixsixfive/phlat#10]
I don't think it is necessary to set the arch to `x86_64` as there is anything to compile. I changed it to `any` and I've just created a package on my Raspberry Pi (Arch Linux ARM).
Do you know any reason not to change it?

https://github.com/sixsixfive/phlat/blob/7042c1f2e1e9da04f0c09dbbb1151a672c7da449/%40extra/.pkgs/PKGBUILD/PKGBUILD#L7

**Comment by sixsixfive** [comment]
no problem - guess it was because arch/manjaro does not officially support arm.
