### ISSUE TITLE
Phlat-Lighter bug?

### ISSUE THREAD

**Issue by chuutatsu** [sixsixfive/phlat#11]
After reinstalling Phlat themes using PKGBUILD from this repository, I found something odd.
Is Phlat-Lighter updated to look like this in Thunar?
![screenshot_2017-09-04_21-26-12](https://user-images.githubusercontent.com/24815847/30030553-13e3194e-91b8-11e7-8b65-8123fa66976e.png)

The last time I used Phlat-Lighter (before updating), it looked like a light version of Phlat (Dark). There is no double middle border inside Thunar, between folder list on the left and files on the right.
![screenshot_2017-09-04_21-27-38](https://user-images.githubusercontent.com/24815847/30030690-a60e2e6c-91b8-11e7-8c4e-a54843ca8474.png)

I am using Xfce with GTK 3.22.

**Comment by sixsixfive** [comment]
Sorry to say but i will probably drop the light version, since there are enough alternatives and i will concentrate on the dark theme ;(

**Comment by chuutatsu** [comment]
That's unfortunate... though the dark theme is still nice and usable.

Thanks for confirmation.
