### ISSUE TITLE
The tabs in phlat-lighter is not styled.

### ISSUE THREAD

**Issue by chuutatsu** [sixsixfive/phlat#6]
I am using the latest phlat version and GTK 3.22. After changing Phlat's default color to any color, the appearance of tabs goes like this:

![screenshot_2017-08-15_20-16-55](https://user-images.githubusercontent.com/24815847/29317581-c7ceaa1c-81f6-11e7-98c9-2d057f18a766.png)

 I ran the changecolor.sh properly. 

Is this because I am not using YAD?

**Comment by sixsixfive** [comment]
xfce still uses gtk2 so you need the pixbuf and murrine engine with svg support, yad is not needed just recommended

**Comment by chuutatsu** [comment]
I have found the solution before I replied this.

I didn't realize that it has PKGBUILD before, so I tried to reinstall by using PKGBUILD method. I used Manjaro Xfce.

I had to use sudo to execute changecolor script (because pacman had the theme installed in /usr/share/themes), and it finally worked correctly somehow.

I close this.
