### ISSUE TITLE
Notification Popup Question

### ISSUE THREAD

**Issue by chuutatsu** [sixsixfive/phlat#8]
Just a question...
After applying the phlat-lighter theme, the Xfce's notification popup background becomes gray.
Is that grayness a part of phlat itself? Or just a bug?
Here is the screenshot.
![12](https://user-images.githubusercontent.com/24815847/29439424-b1f057e8-83e7-11e7-9056-e37e09d47b39.png)

**Comment by sixsixfive** [comment]
a bug -  thx, fixed (=

**Comment by chuutatsu** [comment]
Thank you! I'll reinstall the theme.
