### ISSUE TITLE
LightDM Support and Issue

### ISSUE THREAD

**Issue by chuutatsu** [sixsixfive/phlat#9]
A bunch of quick question and issue.
1. Is this theme supports LightDM? 
2. When using light Phlat theme in LightDM, I got white login box AND **gray** panel. Is this intentional (again)? Or a bug?

(When using dark Phlat theme, the login box and the panel are all black and correct though.)
Sorry I can't send the screenshot.

**Comment by sixsixfive** [comment]
>Is this theme supports LightDM?

Yes it does

>When using light Phlat theme in LightDM, I got white login box AND gray panel. Is this intentional (again)? Or a bug?

its another bug, the light theme is new and still not fully tested sorry - fixed

**Comment by chuutatsu** [comment]
Alright, thanks again.
